---------------------------------------
-- CTA PROJECT INTERVIEW TYPE QUESTIONS 
--   MOCK QUESTIONS (35 QUESTIONS)  ---
---------------------------------------

-- ROUND 1: BASIC CORE SQL QUERIES(10 QUESTIONS)

--1.List all customers from "Mumbai" with gold membership

select*from customers
where city='Mumbai' and membership='Gold';

--2.Find the total number of orders placed in 2024

select count(order_id) as no_of_orders from orders 
where year(order_date)=2024;

--3.Show all products priced above 5000 sorted highest to lowest

select product_name,price from products
where price>5000
order by price desc;

--4. Find all orders that are pending  or cancelled

select*from orders
where status IN('Pending','Cancelled');

--5.Count how many members belong to each membership type

select count(customer_id) as mem_cnt,membership from customers 
group by membership;

--6.Find single most expensive order placed

select top 1 order_id,amount from orders 
order by amount desc;


--7.List all the customers who placed orders from Ahmedabad, Surat and Vadodra

select*from customers
where city IN( 'Ahmedabad','Surat','Vadodra');

--8.Find all orders placed in november & december

select*from orders 
where month(order_date) IN (11,12)
order by order_date;

--9.Show the average order value for completed orders

select avg(amount) as AOV from orders
where status='Completed';

--10.List the products the belong to Electronics or Sports Category,sorted by price

select product_name,price,category from products 
where category in ('Electronics','Sports')
order by price;

-- ROUND 2 INTERMEDIATE SQL QUERIES (12 Questions)


--11.Total Revenue generated by City(completed Orders)

select c.city,sum(o.amount) as total_revenue from 
customers c join orders o on c.customer_id=o.customer_id
where o.status='Completed'
group by c.city
order by total_revenue desc;

--12.Find customers who placed more than 5 orders

select c.name,count(o.order_id) as order_count from
customers c join orders o on c.customer_id=o.customer_id
group by c.name
having count(o.order_id)>5

--13.Payment method split- count and percentgae of Payment method

 select payment_method,count(payment_method) as count_per_payment_method , 
 cast(count(payment_method)*100/sum(count(*)) over() as decimal(10,2)) as percentage_share
 from payments
 group by payment_method

 --14. Find Customers who never placed an order

 select c.name,o.order_id from 
 customers c join orders o on c.customer_id=o.customer_id
 where o.order_id is null
 order by c.customer_id;

 --15.Top 5 best products by quantity sold

 select top 5 p.product_name,count(oi.quantity) as quantity_sold
 from products p join order_items oi on p.product_id=oi.product_id
 group by p.product_name
 order by quantity_sold desc;
 

 --16.Average Order Value by membershipp type- comparision of all tiers

 select c.membership as tier,cast(avg(o.amount) as decimal(10,2)) as avg_Tier_orderamount from 
 customers c join orders o on c.customer_id=o.customer_id
 group by c.membership

 --17.Monthly revenue for 2024

 select datename(month,order_date) as month_name,sum(amount) as monthly_revenue
 from orders
 where year(order_date) in (2024)
 group by datename(month,order_date),month(order_date)
 order by month(order_date);

 --18.Cancellation Rate per city- which city cancels the most

 select c.city,count(o.status) as failed_orders , cast(count(o.status)*100/sum(count(*)) over () as decimal(10,2)) as failure_rate
 from customers c join orders o on c.customer_id=o.customer_id
 where status in('Cancelled')
 group by c.city
 order by failed_orders desc;
 
 --19.Find second highest order amount without using top 2

with second_highest_order_amount as 
(select customer_id,order_id,amount,
dense_rank() over(order by amount desc) as rnk
from orders )

select customer_id,order_id,amount,rnk
from second_highest_order_amount
where rnk=2;

--20. Which product category generates highest per units sold 

select top 1 p.product_name,p.category,sum(oi.quantity) as quantities_sold,sum(p.price) as revenue_units_sold
from products p join order_items oi on p.product_id=oi.product_id
group by p.product_name,p.category
order by revenue_units_sold desc;

--21.Select customers whose average spending is more that average order value

select c.name,sum(o.amount) as total_customer_spending 
from customers c join orders o on c.customer_id=o.customer_id
group by c.name,c.customer_id
having sum(o.amount)>(
   select cast(avg(amount) as decimal(10,2)) as avg_orderamount from orders
   );
 
 --22.Full order details- customer name, order date, product names, quantity and payment method

 select c.name, o.order_date,p.product_name,oi.quantity,pp.payment_method from 
 customers c join orders o on c.customer_id=o.customer_id
 join  order_items oi on o.order_id=oi.order_id
 join products p on oi.product_id=p.product_id
 join payments pp on o.order_id=pp.order_id;


 --Round 3  SQL ADVANCES QUERIES ( 8 QUESTIONS)

--23.Rank customers by their total spend- calculate their dense rank and percentile

with spending_listing as (
select c.name,sum(o.amount) as total_spent,
dense_rank() over(order by sum(o.amount) desc) as spent_rnk
from customers c join orders o on c.customer_id=o.customer_id
group by c.customer_id,c.name
),

RankingStats as(
select *,max(spent_rnk) over() as max_rnk from
spending_listing 
)

select name,total_spent,spent_rnk,
CAST((1-(spent_rnk - 1.0) / max_rnk) * 100 AS DECIMAL(10,2)) AS spend_percentile, -- the bottom-up logic
cast((spent_rnk-1.0)/(max_rnk-1.0)*100 as decimal(10,2)) as spent_percentiletopdown -- the top down logic
from RankingStats
order by spent_rnk ;

--24. Month over Month revenue growth percentage from each month 

WITH MonthlyRevenue AS (
    SELECT 
        MONTH(order_date) AS MonthNumber, -- Added this to keep the sort order
        DATENAME(MONTH, order_date) AS months, 
        SUM(amount) AS monthly_Revenue
    FROM orders 
    GROUP BY MONTH(order_date), DATENAME(MONTH, order_date)
)
SELECT 
    months,
    monthly_Revenue,
    LAG(monthly_Revenue) OVER (ORDER BY MonthNumber) AS Previous_Month_Revenue,
    -- Fixed the Parentheses: (Current - Prev) / Prev * 100
    CAST(
        (monthly_Revenue - LAG(monthly_Revenue) OVER (ORDER BY MonthNumber)) 
        / NULLIF(LAG(monthly_Revenue) OVER (ORDER BY MonthNumber), 0) -- Added NULLIF to prevent "Divide by Zero" error
        * 100 
    AS DECIMAL(10,2)) AS MoM_Growth_Percentage
FROM MonthlyRevenue
ORDER BY MonthNumber;

 -- 25. Running Cumulative Revenue 
-- Goal: Show how revenue builds up month by month (Rolling Total)
WITH MonthlyRev AS (
    SELECT 
        MONTH(order_date) as MonthNum,
        DATENAME(MONTH, order_date) as MonthName,
        SUM(amount) as Revenue
    FROM orders
    GROUP BY MONTH(order_date), DATENAME(MONTH, order_date)
)
SELECT 
    MonthName,
    Revenue,
    SUM(Revenue) OVER (ORDER BY MonthNum) AS Cumulative_Revenue
FROM MonthlyRev
ORDER BY MonthNum;

--26. For each customer, show their first order day,last order day , day between first and last 

select c.customer_id,c.name,
min(o.order_date) as first_order_date,
max(o.order_date) as latest_order_date,
datediff(day,min(o.order_date),max(o.order_date)) as duration
from customers c join orders o on c.customer_id=o.customer_id
group by c.name,c.customer_id
order by duration desc;

--27.For each order show the previous order amount by the customer 

SELECT 
    c.name,
    o.order_id,
    o.order_date,
    o.amount AS current_order_amount,
    -- Using LAG to peek at the previous row within the customer's partition
    LAG(o.amount) OVER (PARTITION BY o.customer_id ORDER BY o.order_date) AS previous_order_amount
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
ORDER BY c.name, o.order_date;

--28. Find the customers who placed an order in 2024 not in 2025

select c.name,c.customer_id
from customers c join orders o on c.customer_id=o.customer_id
where year(o.order_date)=2024 and year(o.order_date) !=2025
group by c.name,c.customer_id;

--29.3 month rolling average revenue -- smooth out seasonal spikes

WITH MonthlyRevenue AS (
    SELECT 
        MONTH(order_date) AS MonthNum,
        DATENAME(MONTH, order_date) AS MonthName,
        SUM(amount) AS TotalRevenue
    FROM orders
    GROUP BY MONTH(order_date), DATENAME(MONTH, order_date)
)
SELECT 
    MonthName,
    TotalRevenue,
    -- Using AVG with a frame specification to look back 2 rows plus the current row
    AVG(TotalRevenue) OVER (
        ORDER BY MonthNum 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS Rolling_Avg_3_Month
FROM MonthlyRevenue
ORDER BY MonthNum;

--30. Identify the top product in each category

with product_revenue as (
   select p.product_name,p.category,sum(p.price*oi.quantity) as product_Revenue,
   dense_rank() over(partition by p.category order by sum(p.price*oi.quantity)desc) as rnk
   from products p join order_items oi on p.product_id=oi.product_id
   group by p.product_name,p.category

)

select product_name,category,
Product_revenue
from product_revenue 
where rnk=1
group by Product_Revenue,product_name,category;

-- Round 4 Expert Level Queries

--31. Full RFM Scoring with business segment labels 

WITH customer_analysis AS (
    SELECT 
        c.name,
        c.customer_id,
        -- Correct Recency: Days since the absolute last order in the dataset
        DATEDIFF(day, MAX(o.order_date), (SELECT MAX(order_date) FROM orders)) AS recency,
        COUNT(o.order_id) AS frequency,
        SUM(o.amount) AS monetary
    FROM customers c 
    JOIN orders o ON c.customer_id = o.customer_id
    WHERE o.status = 'Completed'
    GROUP BY c.name, c.customer_id
),
RFM_scores AS (
    SELECT 
        customer_id,
        -- R_score: Lower recency (days) = Higher Score (5)
        NTILE(5) OVER(ORDER BY recency DESC) AS R_score,
        NTILE(5) OVER(ORDER BY frequency DESC) AS F_score,
        NTILE(5) OVER(ORDER BY monetary DESC) AS M_score
    FROM customer_analysis
) 
SELECT 
    c.name,
    c.recency,
    c.frequency,
    c.monetary,
    r.R_score,
    r.F_score,
    r.M_score,
    CASE 
        WHEN R_score >= 4 AND F_score >= 4 AND M_score >= 4 THEN 'Champions'
        WHEN R_score >= 4 AND F_score >= 2 THEN 'Loyalists'
        WHEN R_score <= 2 AND F_score >= 4 THEN 'At Risk - Can''t Lose'
        WHEN R_score <= 2 AND F_score <= 2 THEN 'Hibernating'
        ELSE 'Regular'
    END AS customer_segment
FROM RFM_scores r 
JOIN customer_analysis c ON r.customer_id = c.customer_id
ORDER BY R_score DESC, F_score DESC;


--32.Year over Year comparision - 2023 vs 2024 vs 2025 side by side

WITH Yearly_Stats AS (
    SELECT 
        YEAR(order_date) AS order_year,
        SUM(amount) AS yearly_revenue,
        COUNT(order_id) AS total_orders,
        CAST(AVG(amount) AS DECIMAL(10,2)) AS aov
    FROM orders
    WHERE status = 'Completed'
    GROUP BY YEAR(order_date)
)
SELECT 
    order_year,
    yearly_revenue,
    -- Pulling the previous year's revenue using LAG
    LAG(yearly_revenue) OVER (ORDER BY order_year) AS prev_year_revenue,
    -- Calculating YoY Growth %
    CAST(
        (yearly_revenue - LAG(yearly_revenue) OVER (ORDER BY order_year)) 
        * 100.0 / NULLIF(LAG(yearly_revenue) OVER (ORDER BY order_year), 0) 
    AS DECIMAL(10,2)) AS yoy_growth_pct,
    aov,
    total_orders
FROM Yearly_Stats
ORDER BY order_year;

-- 33. Expert Level: Customer Cohort Retention Analysis
-- Goal: See what % of customers acquired in a specific year returned in following years
WITH Acquisition_Year AS (
    -- Step 1: Find the first year for every customer
    SELECT 
        customer_id, 
        MIN(YEAR(order_date)) AS first_year
    FROM orders
    GROUP BY customer_id
),
Returning_Customers AS (
    -- Step 2: Get unique years each customer placed an order
    SELECT DISTINCT 
        customer_id, 
        YEAR(order_date) AS active_year
    FROM orders
)
SELECT 
    a.first_year AS cohort_year,
    COUNT(DISTINCT a.customer_id) AS total_acquired,
    -- Retention in 2024
    CAST(COUNT(DISTINCT CASE WHEN r.active_year = 2024 THEN r.customer_id END) * 100.0 / 
         COUNT(DISTINCT a.customer_id) AS DECIMAL(10,2)) AS retention_rate_2024_pct,
    -- Retention in 2025
    CAST(COUNT(DISTINCT CASE WHEN r.active_year = 2025 THEN r.customer_id END) * 100.0 / 
         COUNT(DISTINCT a.customer_id) AS DECIMAL(10,2)) AS retention_rate_2025_pct
FROM Acquisition_Year a
LEFT JOIN Returning_Customers r ON a.customer_id = r.customer_id 
      AND r.active_year > a.first_year -- Only count years AFTER they were acquired
GROUP BY a.first_year
ORDER BY a.first_year;

-- 34. Expert Level: Payment Leakage & Recovery Report
-- Goal: Identify revenue lost to failures by city/method and estimate recovery value
-- 34. Expert Level: Payment Leakage & Recovery Report (FIXED)
WITH Payment_Audit AS (
    SELECT 
        c.city,
        p.payment_method,
        SUM(o.amount) AS total_attempted_revenue,
        -- CHECK: Does your table use 'Success', 'Completed', or 'Paid'? 
        -- Using 'Success' here as it's the most common partner to 'Failed'
        SUM(CASE WHEN p.payment_status IN ('Success', 'Completed') THEN o.amount ELSE 0 END) AS successful_revenue,
        SUM(CASE WHEN p.payment_status = 'Failed' THEN o.amount ELSE 0 END) AS failed_revenue,
        COUNT(p.payment_id) AS total_transactions
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.city, p.payment_method
)
SELECT 
    city,
    payment_method,
    total_attempted_revenue,
    successful_revenue,
    failed_revenue,
    CAST((failed_revenue * 100.0) / NULLIF(total_attempted_revenue, 0) AS DECIMAL(10,2)) AS leakage_pct,
    CAST(failed_revenue * 0.50 AS DECIMAL(10,2)) AS estimated_recovery_value
FROM Payment_Audit
WHERE total_attempted_revenue > 0
ORDER BY failed_revenue DESC;

-- 35. Final Expert Level: Master Customer Health Scorecard
-- Integrating your CustomerStats logic with Payment and Product depth.
WITH CustomerStats AS (
    SELECT 
        c.customer_id,
        c.name,
        c.city,
        SUM(o.amount) AS Raw_revenue,
        COUNT(o.order_id) AS total_orders,
        DATEDIFF(day, MIN(o.order_date), MAX(o.order_date)) AS active_days,
        -- Global Max Date subquery to fix the previous 'more than 1 value' error
        DATEDIFF(day, MAX(o.order_date), (SELECT MAX(order_date) FROM orders)) AS recency
    FROM customers c 
    JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.name, c.city
),
PaymentStats AS (
    SELECT 
        o.customer_id,
        CAST(SUM(CASE WHEN p.payment_status IN ('Success', 'Completed') THEN 1 ELSE 0 END) * 100.0 / 
             NULLIF(COUNT(p.payment_id), 0) AS DECIMAL(10,2)) AS payment_success_rate,
        SUM(CASE WHEN p.payment_status = 'Failed' THEN o.amount ELSE 0 END) AS leaked_revenue
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY o.customer_id
),
ProductStats AS (
    SELECT 
        o.customer_id,
        COUNT(DISTINCT p.category) AS category_diversity
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY o.customer_id
)
SELECT 
    cs.name,
    cs.city,
    cs.Raw_revenue AS ltv,
    cs.total_orders,
    cs.active_days AS tenure,
    cs.recency,
    ps.payment_success_rate,
    ps.leaked_revenue AS recovery_potential,
    pts.category_diversity,
    -- The Health Label logic based on your integrated stats
    CASE 
        WHEN cs.recency <= 30 AND ps.payment_success_rate >= 90 AND cs.Raw_revenue > 50000 THEN 'Platinum Member'
        WHEN cs.recency > 90 AND cs.Raw_revenue > 30000 THEN 'At Risk / Churning'
        WHEN ps.payment_success_rate < 50 THEN 'High Friction'
        ELSE 'Regular'
    END AS health_status
FROM CustomerStats cs
LEFT JOIN PaymentStats ps ON cs.customer_id = ps.customer_id
LEFT JOIN ProductStats pts ON cs.customer_id = pts.customer_id
ORDER BY cs.Raw_revenue DESC;